/* eslint-disable */
// DO NOT EDIT THIS FILE
// Generated by @graphql-codegen/cli using:
// (npm|yarn|pnpm) run generate
export type ErrorResponse = { fields: Array<string>; message: string }
export type Maybe<T> = T | null
export type InputMaybe<T> = Maybe<T>
export type Exact<T extends { [key: string]: unknown }> = {
  [K in keyof T]: T[K]
}
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]?: Maybe<T[SubKey]>
}
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]: Maybe<T[SubKey]>
}
// Generated on 21.08.2022 18:26

/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string
  String: string
  Boolean: boolean
  Int: number
  Float: number
}

/** An item */
export type Item = {
  __typename?: 'Item'
  id?: Maybe<Scalars['ID']>
  name?: Maybe<Scalars['String']>
}

export type RootQueryType = {
  __typename?: 'RootQueryType'
  /** Test Query */
  item?: Maybe<Item>
}

export type RootQueryTypeItemArgs = {
  id: Scalars['ID']
}

export type TestQueryVariables = Exact<{
  id: Scalars['ID']
}>

export type TestQuery = {
  __typename?: 'RootQueryType'
  item?: { __typename?: 'Item'; name?: string | null } | null
}
