/* eslint-disable */
// DO NOT EDIT THIS FILE
// Generated by @graphql-codegen/cli using:
// (npm|yarn|pnpm) run generate
import * as T from '@interfaces/generated-types'
import { useQuery, UseQueryOptions } from '@tanstack/react-query'
import { fetcher } from '@services/data'
// Generated on 21.08.2022 18:26

export const TestDocument = `
    query Test($id: ID!) {
  item(id: $id) {
    name
  }
}
    `
export const useTestQuery = <TData = T.TestQuery, TError = T.ErrorResponse>(
  variables: T.TestQueryVariables,
  options?: UseQueryOptions<T.TestQuery, TError, TData>
) =>
  useQuery<T.TestQuery, TError, TData>(
    ['Test', variables],
    fetcher<T.TestQuery, T.TestQueryVariables>(TestDocument, variables),
    options
  )
